name: Custom Workflow for part 2

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
    
      # Installe java 8 sur l'agent
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
  
      # Compile notre application
      - name: Build with Maven
        run: mvn -f ../.. --batch-mode --update-snapshots package
